### ISSUE TITLE
This plugin is no longer maintained. The developer recommends using Google reCAPTCHA instead.

### ISSUE THREAD

**Issue by iamkeir** [Simplon-Prod/craft-google-recaptcha#5]
<img width="899" alt="screenshot_374" src="https://user-images.githubusercontent.com/539615/181766100-b6f5fe69-cb7c-42d3-ae8a-b4c55eaad871.png">

Hi there - we have just received the update "This plugin is no longer maintained. The developer recommends using Google reCAPTCHA instead" but the link attached to "Google reCaptcha" links back to the same plugin? Is this a mistake and it is meant to be recommending a different Craft recaptcha plugin?

**Comment by juban** [comment]
Hi @iamkeir 

The new home for this plugin will be https://github.com/juban/craft-google-recaptcha now.
I will continue to support that plugin.
I've reached out the Craft support team in order to fix the issue you refer to migrate the current plugin to different account, but did not get an answer yet.
Sorry for that and thanks for your interest.

**Comment by iamkeir** [comment]
@juban that's even better news :) no problem at all
